from scrap_steam_services.web_page_cleaning.InventoryCleaner import InventoryCleaner
from scrap_steam_services.web_page_cleaning.MarketItemPageCleaner import MarketItemPageCleaner
from scrap_steam_services.web_page_cleaning.MarketMainPageCleaner import MarketMainPageCleaner
from scrap_steam_services.web_page_cleaning.ProfileBadgesPageCleaner import ProfileBadgesPageCleaner
from scrap_steam_services.web_page_cleaning.ProfileGameCardsPageCleaner import ProfileGameCardsPageCleaner
